---
title: An R Markdown document converted from "Fig2_code.ipynb"
output: html_document
---

```{r}
suppressMessages(library(caret))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(ggvenn))
suppressMessages(library(reshape2))
suppressMessages(library(pROC))
suppressMessages(library(magrittr))
suppressMessages(library(tidyr))
suppressMessages(library(stringr))
```

```{r}
gene.list = read.delim("../files_for_manuscript/gencode.biotype.name.key.tsv")
metadata = read.delim("../files_for_manuscript/metadata_discovery.txt")
top = read.delim("../files_for_manuscript/top150genes.csv")
counts_val = read.delim("../files_for_manuscript/count_matrix_validation.txt", row.names=c(1))
metadata_val = read.delim("../files_for_manuscript/metadata_validation.txt", header=T)
```

## GREEDY FORWARD SEARCH

```{r}
set.seed(42)
counts = read.delim("../files_for_manuscript/count_matrix.txt", row.names=c(1))
top = read.delim("../files_for_manuscript/top150genes.csv")

gene.list_keep = gene.list[gene.list$gene_name %in% top$x,1]
counts = counts[rownames(counts) %in% gene.list_keep,]

counts= counts %>% edgeR::cpm() %>% t() %>% data.frame()  

counts$Cornell_ID = rownames(counts)
```

```{r}
head(counts)
```

```{r}
train_ind = sample(seq_len(nrow(counts)), size=0.70*nrow(counts))
metadata$sample = paste0(metadata$Cornell_ID, "_combined")

counts_train = counts[train_ind,]
counts_test = counts[-train_ind,]


metadata_train = metadata[metadata$sample %in% rownames(counts_train),]
metadata_test = metadata[metadata$sample %in% rownames(counts_test),]
```

```{r}
metadata_train%>%group_by(Microbiologic.reference.standard) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

metadata_test%>%group_by(Microbiologic.reference.standard) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

```{r}
counts_train.melt = melt(counts_train,id.var="Cornell_ID")
counts_train.melt$Cornell_ID = gsub(counts_train.melt$Cornell_ID, pattern="_combined", replacement="")
counts_train.melt = merge(counts_train.melt, metadata, by="Cornell_ID")
counts_train.melt = merge(counts_train.melt,  gene.list[gene.list$gene_name %in%top$x,1:2], by.x="variable", by.y="gene_id")
```

```{r}
counts_test.melt = melt(counts_test,id.var="Cornell_ID")
counts_test.melt$Cornell_ID = gsub(counts_test.melt$Cornell_ID, pattern="_combined", replacement="")
counts_test.melt = merge(counts_test.melt, metadata, by="Cornell_ID")
counts_test.melt = merge(counts_test.melt,  gene.list[gene.list$gene_name %in% top$x,1:2], by.x="variable", by.y="gene_id")

counts2 = counts_train %>% t() %>% data.frame()
```

```{r}
starts = gene.list[gene.list$gene_name %in% top$x,1]
starts_df = matrix(ncol=4, NA)
colnames(starts_df)=c("gene","auc", "lowci","upci")

for (s in starts){
    df = merge(counts2[rownames(counts2)==s,] %>% t() 
               %>% data.frame()  
               %>% mutate_all(as.numeric) %>%
               mutate( log2( . + 1)) %>% 
               set_colnames("score"), metadata_train, 
               by.x="row.names", by.y="sample")
    auc = auc(df$Microbiologic.reference.standard, as.numeric(df$score))
    lowci = ci.auc(df$Microbiologic.reference.standard, as.numeric(df$score))[1]
    upci = ci.auc(df$Microbiologic.reference.standard, as.numeric(df$score))[3]
    starts_df = rbind(starts_df, cbind("gene"=s, "auc"=auc, "lowci" = lowci, "upci" = upci))
}

starts_df = starts_df %>% data.frame() %>% dplyr::arrange(desc(auc)) 



plot_df = matrix(ncol=4, NA)
colnames(plot_df)=c("combination","auc", "lowci","upci")

plot_df = rbind(plot_df, cbind("combination"=starts_df[1,1], "auc"=starts_df[1,2], "lowci" = starts_df[1,3], "upci"=starts_df[1,4]))

best_auc = plot_df %>% data.frame() %>% filter(row_number()==n())
best_auc = best_auc$auc
best_auc
```

```{r}
res = counts_train.melt %>% group_by(variable,Microbiologic.reference.standard) %>% summarise(val = mean(value))
res2 = dcast(res, variable ~ Microbiologic.reference.standard)
res2$diff = ifelse((res2$`TB Positive` - res2$`TB Negative` > 0), "up", "down")
```

```{r}
df2 = matrix(ncol=4,NA)
colnames(df2)=c("combination","auc", "lowci","upci")

start = plot_df[2,1]
rest = starts[!(starts %in% start)]

for (r in 1:length(rest)){
    
    comb = c(start,rest[r])
    
    pos = res2[res2$diff == "up",] %>% filter(variable %in% comb) %>% pull(variable)
    neg =res2[res2$diff == "down",] %>% filter(variable %in% comb)%>% pull(variable)


    if (length(pos)==1){
        pos_counts =counts2[rownames(counts2) %in% pos,]   %>% data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1))%>% 
        t()%>% set_colnames("pos_score")
    } else if (length(pos)>1) {
        pos_counts =counts2[rownames(counts2) %in% pos,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
       mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("pos_score")      
    } else{
        pos_counts=NA
    }
    
    if (length(neg)==1){
        neg_counts =counts2[rownames(counts2) %in% neg,]   %>% data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1))%>%
        t() %>%
        set_colnames("neg_score")
    } else if (length(neg)>1) {
        neg_counts =counts2[rownames(counts2) %in% neg,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
       mutate( log2( . + 1))%>%
        summarise_all(mean) %>% t() %>% set_colnames("neg_score") 
    } else {
        neg_counts = NA
    }
    
    
    if (!is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts,neg_counts, by="row.names")
        df_test = merge(df_test, metadata_train, by.x="Row.names", by.y="sample")

        df_test$score = df_test$pos_score - df_test$neg_score
        auc = auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))
        lowci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[3]
        
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci" = lowci, "upci"=upci))
    } else if (is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts, metadata_train, by.x="row.names", by.y="sample")

        df_test$score = df_test$pos_score
        auc = auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))
    lowci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[3]
        
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci"=lowci, "upci"=upci))
    } else {
        df_test = merge(neg_counts, metadata_train, by.x="row.names", by.y="sample")

        df_test$score = df_test$neg_score
        auc = auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))
       lowci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, as.numeric(df_test$score))[3]
        
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci"=lowci, "upci"=upci))
    }
}
```

```{r}
while (!is.na(best_auc)){
    sorted_df = df2 %>% data.frame()%>% filter(as.numeric(auc) > best_auc) %>% arrange(desc(auc))
    new_start = unlist(str_split(sorted_df[1,1], "_"))
    new_rest = starts[!(starts %in% new_start)]

    df2 = matrix(ncol=4,NA)
    colnames(df2)=c("combination","auc", "lowci", "upci")
    best_auc = as.numeric(sorted_df[1,2])
    plot_df = rbind(plot_df, cbind("combination"=sorted_df[1,1], "auc"=best_auc, "lowci" = sorted_df[1,3], "upci" = sorted_df[1,4]))
    
    for (r in 1:length(new_rest)){
    comb = c(new_start,new_rest[r])
    
    pos = res2[res2$diff == "up",] %>% filter(variable %in% comb) %>% pull(variable)
    neg =res2[res2$diff == "down",] %>% filter(variable %in% comb)%>% pull(variable)


    if (length(pos)==1){
        pos_counts =counts2[rownames(counts2) %in% pos,]   %>% data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1))%>% 
        t()%>% set_colnames("pos_score")
    } else if (length(pos)>1) {
        pos_counts =counts2[rownames(counts2) %in% pos,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("pos_score")      
    } else{
        pos_counts=NA
    }
    
    if (length(neg)==1){
        neg_counts =counts2[rownames(counts2) %in% neg,]   %>% data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1)) %>% 
        t() %>%
        set_colnames("neg_score")
    } else if (length(neg)>1) {
        neg_counts =counts2[rownames(counts2) %in% neg,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1))%>% 
        summarise_all(mean) %>% t() %>% set_colnames("neg_score") 
    } else {
        neg_counts = NA
    }
    
    
    
    if (!is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts,neg_counts, by="row.names")
        df_test = merge(df_test, metadata_train, by.x="Row.names", by.y="sample")

        df_test$score = df_test$pos_score - df_test$neg_score
        auc = auc(df_test$Microbiologic.reference.standard, df_test$score)
        lowci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[3]
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci"=lowci, "upci"=upci))
    } else if (is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts, metadata_train, by.x="row.names", by.y="sample")

        df_test$score = df_test$pos_score
        auc = auc(df_test$Microbiologic.reference.standard, df_test$score)
        
        
        lowci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[3]
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci"=lowci, "upci"=upci))
    } else {
        df_test = merge(neg_counts, metadata_train, by.x="row.names", by.y="sample")

        df_test$score = df_test$neg_score
        auc = auc(df_test$Microbiologic.reference.standard, df_test$score)
        
        
        lowci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[1]
        upci = ci.auc(df_test$Microbiologic.reference.standard, df_test$score)[3]
        df2 = rbind(df2, cbind("combination" = paste(comb, collapse="_"),"auc"=auc, "lowci"=lowci, "upci"=upci))
    }
}
    
    plot.roc(df_test$Microbiologic.reference.standard, df_test$score, print.auc=TRUE)
}

```

## FIG 2A

```{r}
plot_df2 = data.frame(plot_df)
plot_df2 = plot_df2[!is.na(plot_df2$auc),]
plot_df2$iteration = c(seq(1:dim(plot_df2)[1]))
plot_df2$last = sapply(strsplit(plot_df2$combination ,"_"), tail, 1)
plot_df2 = merge(plot_df2, gene.list, by.x="last", by.y="gene_id")
options(repr.plot.height=1.5, repr.plot.width=1.5)
#pdf("gfs_genes.pdf", height=1.2, width=1.2)
ggplot(plot_df2, aes(x=iteration, y=as.numeric(auc), label=gene_name))+ geom_line(color="grey50")+
theme_bw(base_size=6) + xlab("# Genes in Model") + ylab("AUC") + 
geom_text(hjust=0.5, vjust=0.5, size=2, color="deeppink")+
scale_x_continuous(breaks=scales::pretty_breaks()) +
ylab("ROC-AUC") + xlab("Iteration") +
theme(axis.text=element_text(size=6, color="black"),
     axis.title=element_text(size=8, color="black"))
#dev.off()
```

```{r}
best = plot_df2 %>% arrange(iteration) %>% filter(row_number() ==n())
best = best[1,2]
best_genes = unlist(str_split(best,"_"))
counts_test = counts_test %>% t() %>% data.frame()


    pos = res2[res2$diff == "up",] %>% filter(variable %in% best_genes) %>% pull(variable)
    neg =res2[res2$diff == "down",] %>% filter(variable %in% best_genes)%>% pull(variable)

    if (length(pos)==1){
    
        pos_counts = counts_test[rownames(counts_test)%in% pos,] %>% data.frame() %>% mutate_all(as.numeric)  %>%
        mutate( log2( . + 1)) %>%  
        t() %>%
        set_colnames("pos_score")
    } else if (length(pos)>1) {
         pos_counts =counts_test[rownames(counts_test) %in% pos,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>%
        mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("pos_score")      

    } else{
        pos_counts=NA
    }
    
    if (length(neg)==1){
       neg_counts = counts_test[rownames(counts_test)%in% neg,] %>% data.frame() %>% mutate_all(as.numeric)  %>% 
        mutate( log2( . + 1)) %>%  
        t() %>%
        set_colnames("neg_score")
    } else if (length(neg)>1) {
         neg_counts =counts_test[rownames(counts_test) %in% neg,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("neg_score")      

    } else {
        neg_counts = NA
    }
    
    
    if (!is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts,neg_counts, by="row.names")
        df_test = merge(df_test, metadata_test, by.x="Row.names", by.y="sample")

        df_test$score = df_test$pos_score - df_test$neg_score
        auc_test = auc(df_test$Microbiologic.reference.standard, df_test$score)
        
    } else if (is.na(neg_counts) & !is.na(pos_counts)){
        df_test = merge(pos_counts, metadata_test, by.x="row.names", by.y="sample")

        df_test$score = df_test$pos_score
        auc_test = auc(df_test$Microbiologic.reference.standard, df_test$score)
        
    } else {
        df_test = merge(neg_counts, metadata_test, by.x="row.names", by.y="sample")

        df_test$score = df_test$neg_score
        auc_test = auc(df_test$Microbiologic.reference.standard, df_test$score)
        
    }


roc_test = roc(df_test$Microbiologic.reference.standard, df_test$score)
```

```{r}
best = plot_df2 %>% arrange(iteration) %>% filter(row_number() ==n())
best = best[1,2]
best_genes = unlist(str_split(best,"_"))


    pos = res2[res2$diff == "up",] %>% filter(variable %in% best_genes) %>% pull(variable)
    neg =res2[res2$diff == "down",] %>% filter(variable %in% best_genes)%>% pull(variable)

    if (length(pos)==1){
    
        pos_counts = counts2[rownames(counts2)%in% pos,] %>% data.frame() %>% mutate_all(as.numeric)  %>%
        mutate( log2( . + 1)) %>% 
        t() %>%
        set_colnames("pos_score")
    } else if (length(pos)>1) {
         pos_counts =counts2[rownames(counts2) %in% pos,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("pos_score")      

    } else{
        pos_counts=NA
    }
    
    if (length(neg)==1){
       neg_counts = counts2[rownames(counts2)%in% neg,] %>% data.frame() %>% mutate_all(as.numeric)  %>% 
        mutate( log2( . + 1)) %>% 
        t() %>%
        set_colnames("neg_score")
    } else if (length(neg)>1) {
         neg_counts =counts2[rownames(counts2) %in% neg,]   %>% 
        data.frame() %>% mutate_all(as.numeric) %>% 
        mutate( log2( . + 1)) %>% 
        summarise_all(mean) %>% t() %>% set_colnames("neg_score")      

    } else {
        neg_counts = NA
    }
    
    
    if (!is.na(neg_counts) & !is.na(pos_counts)){
        df_train = merge(pos_counts,neg_counts, by="row.names")
        df_train = merge(df_train, metadata_train, by.x="Row.names", by.y="sample")

        df_train$score = df_train$pos_score - df_train$neg_score
        auc_train = auc(df_train$Microbiologic.reference.standard, df_train$score)
        
    } else if (is.na(neg_counts) & !is.na(pos_counts)){
        df_train = merge(pos_counts, metadata_train, by.x="row.names", by.y="sample")

        df_train$score = df_train$pos_score
        auc_train = auc(df_train$Microbiologic.reference.standard, df_train$score)
        
    } else {
        df_train = merge(neg_counts, metadata_train, by.x="row.names", by.y="sample")

        df_train$score = df_train$neg_score
        auc_train = auc(df_train$Microbiologic.reference.standard, df_train$score)
        
    }



roc_train = roc(df_train$Microbiologic.reference.standard, df_train$score)
```

```{r}
## Validation

counts_val = merge(counts, counts_val, by="row.names", all=T)
counts_val[is.na(counts_val)]=0
rownames(counts_val)=counts_val$Row.names
counts_val = counts_val[,-1]
counts_val = counts_val[,grepl("TBSQUARE", colnames(counts_val))]


df_val = counts_val[rownames(counts_val) %in% gene.list[gene.list$gene_name %in% top$x,1],] %>% 
edgeR::cpm() %>% data.frame() %>%
filter(rownames(.)%in% best_genes) %>% data.frame() %>% mutate_all(as.numeric) %>% 
mutate( log2( . +1))  %>% summarise_all(mean) %>%
t() %>% data.frame() %>% set_colnames("score" ) %>% tibble::add_column('sample'=rownames( . )) %>%
merge(. , metadata_val, by.x="sample",by.y="Cornell_ID") %>%
mutate(Semiquant.Xpert.result.3 = factor(Semiquant.Xpert.result.3, levels=c("Negative","Low","Medium","High"))) %>%
   group_by(Semiquant.Xpert.result.3, cohort)

roc_val = df_val %>% filter(!is.na(Microbiologic.reference.standard)) %>% 
mutate(Microbiologic.reference.standard = factor(Microbiologic.reference.standard, levels=c("Negative","Positive"))) %>%
roc(Microbiologic.reference.standard, score)

roc_val
```

## FIG 2B

```{r}

options(repr.plot.height=1.6, repr.plot.width=1.6)
ggroc(list("Train"= roc_train, "Test" = roc_test, "Validation"=roc_val), aes=c("color"))  +
    theme_bw(base_size=6) + guides(color="none", linetype="none")+
    geom_line(size=1,alpha=0.5)+ scale_color_manual(values=c("#218380","#B5179E","#F88C1A")) +
xlab("Specificty (%)") + ylab("Sensitivity (%)") +
theme(axis.text=element_text(size=6, color="black"), axis.title=element_text(size=8, color="black"))
```

```{r}
ci.auc(roc_train)
ci.auc(roc_test)
ci.auc(roc_val)
```

## FIG 2C

```{r}
df_val = df_val[,1:7]
df_val$cohort= "Validation"
```

```{r}
youden = coords(roc_train, x="best", input="threshold", best.method="youden")$threshold
```

```{r}
violplot_df = rbind(cbind(df_train[,c(1,2,4)], "cohort"="Train", df_train[,c(10,42,50)]),
cbind(df_test[,c(1,2,4)], "cohort"="Test", df_test[,c(10,42,50)]))
violplot_df$Microbiologic.reference.standard = gsub(violplot_df$Microbiologic.reference.standard, pattern="TB ", replacement="")
colnames(violplot_df)=colnames(df_val)

options(repr.plot.width=3.5, repr.plot.height=1.75)

rbind(violplot_df, df_val) %>% filter(Microbiologic.reference.standard!="") %>% 
mutate(cohort=factor(cohort,levels=c("Train","Test","Validation"))) %>% 
ggplot( aes(x=Microbiologic.reference.standard, y=score)) + 
geom_violin(color=NA, alpha=0.2,aes(fill=Microbiologic.reference.standard)) + theme_bw(base_size=8) +
geom_jitter(aes(color=Microbiologic.reference.standard), size=0.5) + geom_hline(yintercept = youden, linetype="dashed") +
scale_fill_manual(values=c("#2E294E", "#FF70A6"))+ scale_color_manual(values=c("#2E294E", "#FF70A6")) +
theme(legend.position="none", axis.title.x=element_blank(), axis.text=element_text(size=6, color="black"),
     strip.background = element_rect(color="#FFFFFF", fill="#FFFFFF", size=0),
                                 strip.text.x = element_text(size = 8, color = "black"  ),
                                 panel.border = element_rect(colour = "black", fill=NA, size=1)) +
ylab("9-gene TB Score") + facet_wrap(.~cohort) +
scale_x_discrete(labels=c("TB Negative","TB Positive"))
```

## FIG 2D

```{r}
counts_val = read.delim("../files_for_manuscript/count_matrix_validation.txt", row.names=c(1))
metadata_val = read.delim("../files_for_manuscript/metadata_validation.txt", header=T)
counts = read.delim("../files_for_manuscript/count_matrix.txt", row.names=c(1))
```

```{r}
metadata_val$`Semiquant.Xpert.result.3`[metadata_val$Semiquant.Xpert.result.3 == "Trace"]= "Low"
metadata_val$`Semiquant.Xpert.result.3`[metadata_val$Semiquant.Xpert.result.3 == "Very low"]= "Low"
metadata_val$`Semiquant.Xpert.result.3`[metadata_val$Microbiologic.reference.standard == "Negative"]= "Negative"
```

```{r}
counts_all = merge(counts, counts_val, by="row.names", all=T)
counts_all[is.na(counts_all)]=0
rownames(counts_all)=counts_all$Row.names
counts_all = counts_all[,-1]
```

```{r}
gene_counts = counts_all[rownames(counts_all) %in% gene.list[gene.list$gene_name %in% top$x,1],] %>% 
edgeR::cpm() %>% data.frame() %>%
filter(rownames(.)%in% best_genes) %>% data.frame() %>% mutate_all(as.numeric) %>% 
mutate( log2( . +1))  
```

```{r}
gene_counts_plot =gene_counts %>% mutate(gene_id = rownames( .)) %>%
    merge(gene.list[,1:2], ., by="gene_id")  %>%
    melt(. , id.vars=c("gene_id","gene_name")) %>% merge(metadata_val, ., by.x="Cornell_ID", by.y="variable") %>% 
mutate(Semiquant.Xpert.result.3 = factor(Semiquant.Xpert.result.3, levels=c("Negative","Low","Medium","High"))) 
options( repr.plot.width=7, repr.plot.height=2.6)


gene_counts_plot[gene_counts_plot$value!=0,] %>% filter(!is.na(Semiquant.Xpert.result.3)) %>% 
ggplot( aes(x=cohort, y=value, fill=Semiquant.Xpert.result.3))+ geom_boxplot(outlier.size = 0.5, color="black") + 
    theme_bw(base_size=6) + theme(axis.text.x=element_text(color="black"), axis.title.x=element_blank(),
                                  axis.text=element_text( color="black"), 
                                  axis.title=element_text(color="black"), legend.position="none", 
                                  title=element_text(size=6, color="black"), 
                                 strip.background = element_rect(color="#FFFFFF", fill="#FFFFFF", size=0),
                                 strip.text.x = element_text(size = 6, color = "black", face = "bold.italic"  ),
                                 panel.border = element_rect(colour = "black", fill=NA, size=1),
                                 panel.spacing.y = unit(0.15, "mm"),
                                 aspect.ratio=0.8) +
    scale_fill_manual(values=c("#73D2DE","#218380","#FFBC42","#D81159")) + facet_wrap(.~gene_name, scales="free", ncol=5)+
scale_x_discrete(labels=c("END TB", "R2D2", "TB2")) +
ylab("log2(counts per million + 1)")
```

## FIG 2E

```{r}
semiq_counts = counts_all[rownames(counts_all) %in% gene.list[gene.list$gene_name %in% top$x,1],] %>% 
edgeR::cpm() %>% data.frame() %>%
filter(rownames(.)%in% best_genes) %>% data.frame() %>% mutate_all(as.numeric) %>% 
mutate( log2( . +1))  %>% summarise_all(mean) %>%
t() %>% data.frame() %>% set_colnames("score" ) %>% tibble::add_column('sample'=rownames( . )) %>%
merge(. , metadata_val, by.x="sample",by.y="Cornell_ID") %>%
filter(Semiquant.Xpert.result.3 !="") %>% 
mutate(Semiquant.Xpert.result.3 = factor(Semiquant.Xpert.result.3, levels=c("Negative","Low","Medium","High"))) %>%
   group_by(Semiquant.Xpert.result.3, cohort)%>% summarise(mean = mean(score, na.rm = TRUE),
                                                             sd = sd(score, na.rm = TRUE),
                                                             n = n()) %>%
    mutate(se = sd / sqrt(n),
           lower.ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
           upper.ci = mean + qt(1 - (0.05 / 2), n - 1) * se)

semiq_counts$cohort[semiq_counts$cohort=="GHL"]= "END TB"
```

```{r}
options(repr.plot.height=1.6, repr.plot.width=1.9)

semiq_counts %>% 
    mutate(Semiquant.Xpert.result.3 = factor(Semiquant.Xpert.result.3, levels=c("Negative","Low","Medium","High"))) %>%
filter(Semiquant.Xpert.result.3 !="") %>%
    ggplot(aes(x=Semiquant.Xpert.result.3, y=mean, color=cohort, group=cohort)) + 
    geom_line(size=1) + geom_errorbar( aes(ymin=lower.ci, ymax=upper.ci)) + 
 geom_point(size=1) + theme_bw(base_size=6) +
    theme(legend.position="none",
         axis.text=element_text(color="black", size=6),
         axis.title=element_text(color="black",size=8)) +
    xlab("GeneXpert Semiquantitative Result") + ylab("9-gene TB score")  +
    scale_color_manual(values=c("#D81159", "#73D2DE","#96be25"))  +
geom_hline(yintercept=youden, linetype="dashed")
```

## FIG 2F

```{r}
 cxr = read.delim("../files_for_manuscript/validation_cxr.txt")%>% 
    data.frame() %>%
    dplyr::select("Study.ID", "CAD4TB.score", "Lunit.score", "qXR.score") %>%
    mutate(Study.ID = gsub(Study.ID, pattern="R2D204", replacement='TBSQUARE_cfRNA_')) %>%
    mutate(Study.ID = gsub(Study.ID, pattern="$", replacement="_combined")) %>%
    set_colnames(c("Cornell_ID","CAD4TB.score","Lunit.score","qXR.score")) %>%
    rbind(. ,metadata %>% select(Cornell_ID, "CAD4TB.score","Lunit.score","qXR.score")%>% 
mutate(Cornell_ID = gsub(Cornell_ID, pattern="$", replacement="_combined")), by="Cornell_ID") %>% 
merge(., metadata_val[,c(1,3,5)], by="Cornell_ID") %>%
merge(. , rbind(violplot_df, df_val)[,c(1,2)], by.x="Cornell_ID", by.y="sample") %>%
    filter(!is.na(CAD4TB.score))  %>% filter(Microbiologic.reference.standard !="")  %>% 
    reshape2::melt(.,id.vars=c("Cornell_ID","Microbiologic.reference.standard","score", "cohort")) %>%
mutate(value = as.numeric(value)) %>% mutate(variable = gsub(variable, pattern=".score", replacement=" Score"))
```

```{r}
options(repr.plot.height=1.6, repr.plot.width=4.6)

cxr %>% ggplot(aes(x=value, y=score, color=Microbiologic.reference.standard)) + 
geom_point(size=0.5, aes(shape=cohort))+
    theme_bw(base_size=8) + geom_smooth(method="loess", span=2, color="black")+
    theme(legend.position="none", axis.text=element_text(size=6, color="black"), axis.title=element_blank(),
) +ylab("9-gene TB score")+ scale_color_manual(values=c("#433F60", "#FF70A6")) + 
facet_wrap(.~variable, scales="free", strip.position="bottom")+
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside",
      axis.text=element_text(size=6, color="black"),
      axis.title=element_text(size=8, color="black"),
      axis.title.x=element_blank()
  )
```

```{r}
cxr %>% group_by(variable) %>% summarise(cor = cor(value, score, method="pearson"))
```

